apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kp-deployment
  name: kp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kp-deployment
  template:
    metadata:
      labels:
        app: kp-deployment
    spec:
      containers:
      - name: test-flask-pipeline
        image: kpkm25/test-flask-pipeline
        volumeMounts:                    
        - name: vol-html
          mountPath: "/home/parakram"    
        resources: {}                    
      volumes:
      - name: vol-html
        persistentVolumeClaim:
          claimName: pvc
