apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-25T13:44:05Z"
  labels:
    app: kp-deployment
  name: kp-deployment
  namespace: default
  resourceVersion: "17379"
  uid: e300837d-82ce-4418-a78f-3bc4eb0befe8
spec:
  clusterIP: 10.107.239.154
  clusterIPs:
  - 10.107.239.154
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: kp-deployment
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
